// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV-0Gy4Ny9td2l3iJLmIxX6I3YgWoChjU',
    appId: '1:517840735680:web:21e48c80a9df0f3fdc8c25',
    messagingSenderId: '517840735680',
    projectId: 'diplom-c61c5',
    authDomain: 'diplom-c61c5.firebaseapp.com',
    storageBucket: 'diplom-c61c5.firebasestorage.app',
    measurementId: 'G-MZG2KKS99X',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCecbxvzahGatF8w5xr9Y4PrmY6nEw212U',
    appId: '1:517840735680:ios:75a7b0843880de8bdc8c25',
    messagingSenderId: '517840735680',
    projectId: 'diplom-c61c5',
    storageBucket: 'diplom-c61c5.firebasestorage.app',
    iosBundleId: 'com.example.diplom',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCecbxvzahGatF8w5xr9Y4PrmY6nEw212U',
    appId: '1:517840735680:ios:75a7b0843880de8bdc8c25',
    messagingSenderId: '517840735680',
    projectId: 'diplom-c61c5',
    storageBucket: 'diplom-c61c5.firebasestorage.app',
    iosBundleId: 'com.example.diplom',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbme_9SiodTvtdtp4BH03-C2yIznYFmeE',
    appId: '1:517840735680:android:4264382ac3955cd7dc8c25',
    messagingSenderId: '517840735680',
    projectId: 'diplom-c61c5',
    storageBucket: 'diplom-c61c5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV-0Gy4Ny9td2l3iJLmIxX6I3YgWoChjU',
    appId: '1:517840735680:web:891285bdca912570dc8c25',
    messagingSenderId: '517840735680',
    projectId: 'diplom-c61c5',
    authDomain: 'diplom-c61c5.firebaseapp.com',
    storageBucket: 'diplom-c61c5.firebasestorage.app',
    measurementId: 'G-RNM1TYCD36',
  );
}
